### ISSUE TITLE
README fails at "npm run test:cover" step

### ISSUE THREAD

**Issue by trentmc** [oceanprotocol/contracts#275] opened 2021-03-18 08:49 UTC
**Describe the bug**
I get an `ERR!` when running local test coverage.

**To Reproduce**
1. Go through all the steps of the README, using ganache
2. It will fail at the step `npm run test:cover`

**Expected behavior**
It doesn't fail

**Additional context**

I'm in ubuntu version 18.04. npm version 7.6.3. Node versoin 14.16.0.

Traceback:
```console
trentmc@trentmcLnv:~/code/contracts$ npm run test:cover

> @oceanprotocol/contracts@0.5.10 test:cover
> npx truffle run coverage --network coverage


> Using Truffle library from local node_modules.


/home/trentmc/code/contracts/node_modules/truffle/build/webpack:/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:358
                callback(err);
^
Error: Callback was already called.
    at /home/trentmc/code/contracts/node_modules/truffle/build/webpack:/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:43:1
    at WriteStream.<anonymous> (/home/trentmc/code/contracts/node_modules/truffle/build/webpack:/node_modules/merkle-patricia-tree/node_modules/async/lib/async.js:358:1)
    at WriteStream.emit (events.js:315:20)
    at WriteStream.EventEmitter.emit (domain.js:467:12)
    at WriteStream.destroy (/home/trentmc/code/contracts/node_modules/truffle/build/webpack:/node_modules/level-ws/level-ws.js:140:1)
    at finish (internal/streams/writable.js:670:14)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
npm ERR! code 1
npm ERR! path /home/trentmc/code/contracts
npm ERR! command failed
npm ERR! command sh -c npx truffle run coverage --network coverage

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/trentmc/.npm/_logs/2021-03-18T08_45_57_917Z-debug.log
```

**Comment by 0x3bfc** [comment] 2021-03-29 11:40
@trentmc I can not reproduce your error. again it is because of old documentations. You can find below full detailed `test:cover`. But this implies that readme file needs to be updated.

I will close this issue and it should be fixed in #282 

```
yarn test:cover
yarn run v1.22.10
$ npx truffle run coverage --network coverage

> Using Truffle library from local node_modules.

> server:            http://127.0.0.1:8555
> truffle:           v5.2.4
> ganache-core:      v2.13.0
> solidity-coverage: v0.7.5

Network Info
============
> id:      *
> port:    8555
> network: coverage


Instrumenting for coverage...
=============================

> balancer/BConst.sol
> balancer/BFactory.sol
> balancer/BMath.sol
> balancer/BNum.sol
> balancer/BPool.sol
> balancer/BToken.sol
> communityFee/OPFCommunityFeeCollector.sol
> DTFactory.sol
> fixedRate/FixedRateExchange.sol
> interfaces/IERC20Template.sol
> metadata/Metadata.sol
> templates/DataTokenTemplate.sol
> utils/Deployer.sol

Coverage skipped for:
=====================

> Migrations.sol

Compiling your contracts...
===========================
> Compiling ./.coverage_contracts/DTFactory.sol
> Compiling ./.coverage_contracts/Migrations.sol
> Compiling ./.coverage_contracts/balancer/BConst.sol
> Compiling ./.coverage_contracts/balancer/BFactory.sol
> Compiling ./.coverage_contracts/balancer/BMath.sol
> Compiling ./.coverage_contracts/balancer/BNum.sol
> Compiling ./.coverage_contracts/balancer/BPool.sol
> Compiling ./.coverage_contracts/balancer/BToken.sol
> Compiling ./.coverage_contracts/communityFee/OPFCommunityFeeCollector.sol
> Compiling ./.coverage_contracts/fixedRate/FixedRateExchange.sol
> Compiling ./.coverage_contracts/interfaces/IERC20Template.sol
> Compiling ./.coverage_contracts/metadata/Metadata.sol
> Compiling ./.coverage_contracts/templates/DataTokenTemplate.sol
> Compiling ./.coverage_contracts/utils/Deployer.sol
> Compiling openzeppelin-solidity/contracts/GSN/Context.sol
> Compiling openzeppelin-solidity/contracts/math/SafeMath.sol
> Compiling openzeppelin-solidity/contracts/ownership/Ownable.sol
> Compiling openzeppelin-solidity/contracts/token/ERC20/ERC20.sol
> Compiling openzeppelin-solidity/contracts/token/ERC20/IERC20.sol
> Artifacts written to /Users/ahmedali/Desktop/work/ocean/contracts/.coverage_artifacts/contracts
> Compiled successfully using:
   - solc: 0.5.7+commit.6da8b019.Emscripten.clang


Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

writing address.json file: undefined{
  "rinkeby": {
    "DTFactory": "0x3fd7A00106038Fb5c802c6d63fa7147Fe429E83a",
    "BFactory": "0x53eDF9289B0898e1652Ce009AACf8D25fA9A42F8",
    "FixedRateExchange": "0xeD1DfC5F3a589CfC4E8B91C1fbfC18FC6699Fbde",
    "Metadata": "0xFD8a7b6297153397B7eb4356C47dbd381d58bFF4",
    "Ocean": "0x8967BCF84170c91B0d24D4302C2376283b0B3a07"
  },
  "ropsten": {
    "DTFactory": "0x6ebcCa6df2CAba986FCF44E64Ee82251c1455Dcc",
    "BFactory": "0x75be6e18c80A487C8b49663bf14f80A6495045B2",
    "FixedRateExchange": "0xA7a711A09396DF82D9be46A26B48BafdB9BB4fA6",
    "Metadata": "0x3cd7Ef1F207E1a46AAd7D5d7F5f0A5cF081Fc726",
    "Ocean": "0x5e8DCB2AfA23844bcc311B00Ad1A0C30025aADE9"
  },
  "development": {
    "DTFactory": "0x626aD26c7Ea494b11DbFd5dD487fA98BA32CaA42",
    "BFactory": "0x5eb4bcA8C86Cba7176eCc014A6D7B44c31aC9460",
    "FixedRateExchange": "0x879a308bD4b73425a03cd63ae1Fe03F3EF93BaF1",
    "Metadata": "0xb49cE3689D956417BEDc9F7d848885F8085B1064",
    "Ocean": "0x10345ffBE11e8724b67ee4bB4d70dD4f8a940D84"
  },
  "mainnet": {
    "DTFactory": "0x57317f97E9EA49eBd19f7c9bB7c180b8cDcbDeB9",
    "BFactory": "0xbe0083053744ECb871510C88dC0f6b77Da162706",
    "FixedRateExchange": "0x608d05214E42722B94a54cF6114d4840FCfF84e1",
    "Metadata": "0x1a4b70d8c9DcA47cD6D0Fb3c52BB8634CA1C0Fdf",
    "Ocean": "0x967da4048cD07aB37855c090aAF366e4ce1b9F48"
  },
  "polygon": {
    "DTFactory": "0xF6410bf5d773C7a41ebFf972f38e7463FA242477",
    "BFactory": "0x69B6E54Ad2b3c2801d11d8Ad56ea1d892555b776",
    "FixedRateExchange": "0x2112Eb973af1DBf83a4f11eda82f7a7527D7Fde5",
    "Metadata": "0x80E63f73cAc60c1662f27D2DFd2EA834acddBaa8",
    "Ocean": "0x282d8efCe846A88B159800bd4130ad77443Fa1A1"
  },
  "undefined": {
    "DTFactory": "0x4cB60c9bE9A07D0b63b17146AA7c046163a03E5F",
    "BFactory": "0xBfefaB610569bdA59f84586dC60dB343b0D70976",
    "FixedRateExchange": "0x2F0D733f76C199e52650e27611fb7F4525018202",
    "Metadata": "0xA9ee3148EBF06f0b46c9eA77D7b32F0dF39D8a9E"
  }
}



  Contract: FixedRateExchange
    ✓ should check that the basetoken contract is initialized
    ✓ should check that the datatoken contract is initialized
    ✓ should check that the fixed rate exchange is activated
    ✓ should check that the exchange has no supply yet (88ms)
    ✓ Alice should mint some datatokens (104ms)
    ✓ Bob should mint some basetokens, bob allows marketplace withdrawal (149ms)
    ✓ Alice should allow fixed rate contract to spend datatokens (74ms)
    ✓ should check that the exchange has supply (133ms)
    ✓ should able to generate exchange id using both baseToken and dataToken
    ✓ should get the exchange rate
    ✓ should exchange owner able to deactivate (142ms)
    ✓ should exchange owner able to activate (128ms)
    ✓ Bob should buy DataTokens using the fixed rate exchange contract (284ms)
    ✓ Exchange owner should change the rate using the fixedRateExchange contract (70ms)
    ✓ should get the new fixed exchange rate
    ✓ Bob should buy DataTokens using the fixed rate exchange contract (329ms)
    ✓ should get the number of exchanges
    ✓ should get exchange information (78ms)
    ✓ should get all exchange IDs (39ms)
    ✓ should fail to create the same exchange by the same user (1230ms)
    ✓ should fail to create new exchange with zero rate

  Contract: Metadata test
    ✓ should publish a metadata (72ms)
    ✓ should update a metadata (75ms)

  Contract: DataTokenTemplate
    ✓ should check that the token contract is initialized
    ✓ should fail to re-initialize the contracts
    ✓ should change minter to a new minter address (136ms)
    ✓ should mint the tokens (94ms)
    ✓ should get the token name (171ms)
    ✓ should get the token symbol
    ✓ should get the token decimals
    ✓ should approve token spending (62ms)
    ✓ should increase token allowance (128ms)
    ✓ should decrease token allowance (117ms)
    ✓ should transfer token tokens to another address (137ms)
    ✓ should transfer token tokens to another address (280ms)
    ✓ should get the total cap
    ✓ should get blob
    ✓ should accept zero marketplace fee (175ms)
    ✓ should start order (301ms)
    ✓ should finish order (234ms)
    ✓ should calculate total fee (55ms)

  Contract: Factory test
    ✓ should create a token and check that it is not a zero address (113ms)
    ✓ should fail on zero template address factory initialization
    ✓ should fail on zero minter address initialization
    ✓ should get the token count
    ✓ should get the token template

  Contract: OPFCommunityFeeCollector
    ✓ Owner should change the collector in CommunityFeeCollector (56ms)
    ✓ Alice should mint some datatokens (68ms)
    ✓ Alice should transfer datatokens to CommunityFeeCollector (87ms)
    ✓ Bob should trigger a withdraw from CommunityFeeCollector (111ms)
Failed as it should
    ✓ Bob should fail to change the collector in CommunityFeeCollector (61ms)
    ✓ should allow ETH withdrawal (114ms)

  Contract: BFactory
    BFactory Tests
      ✓ should create new BPool (106ms)
      ✓ should get BPool

  Contract: BPool
    BToken tests
      ✓ should get name (49ms)
      ✓ should get symbole (245ms)
      ✓ should get decimals
    With fees
      ✓ swapExactAmountIn (266ms)
      ✓ swapExactAmountOut (338ms)
      ✓ joinPool (1371ms)
      ✓ exitPool (806ms)
      ✓ joinswapExternAmountIn (1900ms)
      ✓ joinswapPoolAmountOut (1227ms)
      ✓ exitswapPoolAmountIn (1796ms)
      ✓ exitswapExternAmountOut (1308ms)
      ✓ pAo = joinswapExternAmountIn(joinswapPoolAmountOut(pAo)) (496ms)
      ✓ tAi = joinswapPoolAmountOut(joinswapExternAmountIn(tAi)) (639ms)
      ✓ pAi = exitswapExternAmountOut(exitswapPoolAmountIn(pAi)) (1241ms)
      ✓ tAo = exitswapPoolAmountIn(exitswapExternAmountOut(tAo)) (788ms)
      ✓ isPublicSwap returns true (267ms)
      ✓ should return number of tokens
      ✓ should does 


  72 passing (51s)

-------------------------------|----------|----------|----------|----------|----------------|
File                           |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-------------------------------|----------|----------|----------|----------|----------------|
 contracts/                    |      100 |     62.5 |      100 |      100 |                |
  DTFactory.sol                |      100 |     62.5 |      100 |      100 |                |
 contracts/balancer/           |    82.62 |    43.59 |    73.75 |     83.1 |                |
  BConst.sol                   |      100 |      100 |      100 |      100 |                |
  BFactory.sol                 |      100 |       50 |      100 |      100 |                |
  BMath.sol                    |      100 |      100 |      100 |      100 |                |
  BNum.sol                     |      100 |    65.63 |      100 |      100 |                |
  BPool.sol                    |    79.84 |    40.86 |    68.89 |    80.78 |... 483,484,485 |
  BToken.sol                   |    43.59 |       20 |    56.25 |    43.59 |... 149,150,152 |
 contracts/communityFee/       |      100 |       50 |      100 |      100 |                |
  OPFCommunityFeeCollector.sol |      100 |       50 |      100 |      100 |                |
 contracts/fixedRate/          |    95.56 |    57.14 |      100 |    95.74 |                |
  FixedRateExchange.sol        |    95.56 |    57.14 |      100 |    95.74 |        333,340 |
 contracts/interfaces/         |      100 |      100 |      100 |      100 |                |
  IERC20Template.sol           |      100 |      100 |      100 |      100 |                |
 contracts/metadata/           |      100 |       50 |      100 |      100 |                |
  Metadata.sol                 |      100 |       50 |      100 |      100 |                |
 contracts/templates/          |    95.92 |    61.54 |      100 |      100 |                |
  DataTokenTemplate.sol        |    95.92 |    61.54 |      100 |      100 |                |
 contracts/utils/              |      100 |      100 |      100 |      100 |                |
  Deployer.sol                 |      100 |      100 |      100 |      100 |                |
-------------------------------|----------|----------|----------|----------|----------------|
All files                      |    85.77 |    47.06 |    83.33 |    86.61 |                |
-------------------------------|----------|----------|----------|----------|----------------|

> Istanbul reports written to ./coverage/ and ./coverage.json
> solidity-coverage cleaning up, shutting down ganache server
✨  Done in 89.07s.
```

**Closed by 0x3bfc** 2021-03-29 11:40 UTC
Labels: bug
